name: CI

# Allows you to run this workflow manually from the Actions tab
on: [push, pull_request, workflow_dispatch]
# Controls when the action will run. 

jobs:
  # Allows you to run this workflow manually from the Actions tab
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11-dev"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Know your environment
      run: |
        cd $GITHUB_WORKSPACE
        echo
        ls -F
        echo
        env
    - name: Test with tox
      run: tox
